# Generated by Django 2.2.4 on 2019-10-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_quality_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('questions', models.CharField(max_length=255)),
                ('show', models.BooleanField()),
            ],
        ),
    ]
