# Generated by Django 2.2.4 on 2019-09-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_quality_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
